Adding step02 in line with BOT EO run plan
lsst-camera-dh/bot-eotest-configs pull request #12
Opened 2024-08-18 20:06 UTC by seanmacb

File structure determined from [confluence page](https://confluence.lsstcorp.org/display/CAM/Reverification+at+summit+plan)

Output from cfg_interp_Run7.py, columns correspond to time in minutes, number of acquisitions, total image voltage

```
|B_protocol.cfg                     |    89.3 |   258 |  3.87 |
|B_protocol_excl_light.cfg          |    38.4 |    30 |  0.45 |
|C_protocol.cfg                     |    38.0 |   117 |  1.75 |
|D_protocol.cfg                     |    18.6 |    88 |  1.32 |
|sflat.cfg                          |    12.1 |    45 |  0.67 |
|test_flat.cfg                      |     0.9 |     3 |  0.04 |
```

2024-08-19 00:01 UTC, seanmacb commented
`FILTERCONFIG` will need a new path

2024-08-19 00:33 UTC, seanmacb commented
Output from `cfg_interp_Run7.py` unchanged

2024-08-19 16:18 UTC, jchiang87 requested changes
Please update all of the `FILTERCONFIG` paths and remove `Run7/calib.cfg` if it will be the same for all steps.

2024-08-21 19:36 UTC, jchiang87 requested changes
Please rebase to the current master in addition to the items I noted below.

2024-08-21 19:36 UTC, jchiang87 commented on .github/workflows/ci.yaml
> +<<<<<<< HEAD
There are rebase conflicts in this file that need to be cleaned up.

2024-08-21 19:36 UTC, jchiang87 commented on Run7/step02/B_protocol.cfg
> +# ND_OD1.0 and empty (568-1090 e/pixel)
Similar to one of Seth's requests for the step01 cfg files, the duplicate signal levels below can be removed, in addition to this comment.

2024-08-21 19:36 UTC, jchiang87 commented on Run7/step02/C_protocol.cfg
> +#      nm750  50000    10  empty    # wavelength filter, signal(e-), count, ND filter#
I think these lines can be deleted.

2024-08-21 19:36 UTC, jchiang87 commented on Run7/step02/C_protocol.cfg
> +# ND_OD1.0 and empty (568-1090 e/pixel)
Please update the comment to remove the reference to overlapping pairs.  (I don't see any implemented below.)

2024-08-21 19:36 UTC, jchiang87 commented on Run7/step02/D_protocol.cfg
> +# ND_OD1.0 and empty (568-1090 e/pixel)
Please update the comment.

2024-08-21 19:47 UTC, jchiang87 commented on Run7/calib.cfg
It just occurred to me that once this branch is merged in the usual way, this file will be deleted from master.  I think you should restore this file to the original version so that its deletion doesn't appear here (and then fix up any issues when you rebase).  The same applies to the PRs for the other steps.

2024-08-23 20:48 UTC, jchiang87 approved these changes
One small comment, otherwise looks good.

2024-08-23 20:48 UTC, jchiang87 commented on .github/workflows/ci.yaml
> +
It would be great to avoid non-functional changes like this.

2024-08-23 21:32 UTC, merged