Run7/step11
lsst-camera-dh/bot-eotest-configs pull request #14
Opened 2024-08-18 20:38 UTC by seanmacb

File structure determined from [confluence page](https://confluence.lsstcorp.org/display/CAM/Reverification+at+summit+plan)

Output from cfg_interp_Run7.py, columns correspond to time in minutes, number of acquisitions, total image voltage

```
|B_Protocol_PTC.cfg                 |    29.4 |   138 |  2.07 |
|Dense_Linear_PTC.cfg               |   192.0 |   900 | 13.50 |
|Dense_Log_PTC.cfg                  |    94.1 |   441 |  6.61 |
|Dense_PTC_blue.cfg                 |   267.5 |  1254 | 18.81 |
|Dense_PTC_nm750.cfg                |   265.0 |  1242 | 18.63 |
|Dense_PTC_nm850.cfg                |   265.0 |  1242 | 18.63 |
|Dense_PTC_nm960.cfg                |   265.0 |  1242 | 18.63 |
|Dense_PTC_red.cfg                  |   265.0 |  1242 | 18.63 |
|Dense_PTC_uv.cfg                   |   265.0 |  1242 | 18.63 |
|Super_Dense_PTC.cfg                |   649.0 |  3042 | 45.63 |```

2024-08-19 00:12 UTC, seanmacb commented
Will need new path for `FILTERCONFIG`

2024-08-19 00:27 UTC, seanmacb commented
Updated parser results

`
|B_Protocol_PTC.cfg                 |     0.6 |     3 |  0.04 |
|Dense_Linear_PTC.cfg               |     0.6 |     3 |  0.04 |
|Dense_Log_PTC.cfg                  |     0.6 |     3 |  0.04 |
|Dense_PTC_blue.cfg                 |     0.6 |     3 |  0.04 |
|Dense_PTC_nm750.cfg                |     0.6 |     3 |  0.04 |
|Dense_PTC_nm850.cfg                |     0.6 |     3 |  0.04 |
|Dense_PTC_nm960.cfg                |     0.6 |     3 |  0.04 |
|Dense_PTC_red.cfg                  |     0.6 |     3 |  0.04 |
|Dense_PTC_uv.cfg                   |     0.6 |     3 |  0.04 |
|Super_Dense_PTC.cfg                |     0.6 |     3 |  0.04 |
`

These do not make a lot of sense, it appears to only be parsing the first entry of each PTC flat config, instead of the full list. I'm guessing this has something to do with the re-ordered flat flux lists, but wonder if it is only for the parser time estimating parser, or would extend to an actual acquisition

2024-08-19 00:35 UTC, seanmacb commented
Interestingly, other reordered PTC flat field lists are being parsed correctly

2024-08-23 21:01 UTC, jchiang87 requested changes
All of the flat acquisition sequences should be randomized.

2024-08-25 19:57 UTC, seanmacb commented
One comment from @aaronroodman about the ordering of flat acquisitions:

> For step 11 let me suggest the following: there are 2 known effects: temperature dependence in the REBs and persistence following saturated flats.  We could avoid both by 1) monotonically increasing flats - to avoid persistence which will only be present when we no longer care and 2) taking 30 minutes or so of 15 second Darks at the beginning to get the system to thermalize.

I can add the dark overhead, but does this sound reasonable @jchiang87 ?

2024-08-25 20:09 UTC, jchiang87 commented
sure, sounds fine.

2024-08-25 20:22 UTC, seanmacb commented
Changes made

2024-08-26 03:22 UTC, jchiang87 requested changes
It looks like the `dark` acquisitions are being taken after the `flat` acquisitions for a number of these .cfg files.

2024-08-26 03:22 UTC, jchiang87 commented on Run7/step11/Dense_Log_PTC.cfg
> +dark
Is the order here correct?

2024-08-26 03:22 UTC, jchiang87 commented on Run7/step11/Dense_PTC_blue.cfg
> +dark
Should `dark` come before `flat` here?

2024-08-26 13:19 UTC, seanmacb commented on Run7/step11/Dense_Log_PTC.cfg
> +dark
You are correct, good catch. I will modify shortly

2024-08-26 14:37 UTC, jchiang87 approved these changes
One more file to fix, otherwise looks fine.

2024-08-26 14:37 UTC, jchiang87 commented on Run7/step11/B_Protocol_PTC.cfg
> +dark
This one still has `dark` after `flat`.

2024-08-26 14:41 UTC, merged