Persistence Configs for Run 7
lsst-camera-dh/bot-eotest-configs pull request #22
Opened 2024-08-27 21:20 UTC by jbanovetz

Three different Persistence Tests for Run 7. I wasn't able to run Seth's timing code, though I am also not sure if it is set up for the new `DARKINTERRUPT` or `DARKINTERRUPTLIST`, which I rely on for these config files.

2024-08-27 22:18 UTC, jchiang87 requested changes
The github actions CI check runs Seth's script as a syntax checker, so you don't need to do that.

I requested a number of changes, the key one being to update the `FILTERCONFIG` values in all three files.

I'm curious why a `flat` acquisition is used for `Persistence_large.cfg`, but `sflat` for the other two.

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_large.cfg
> +#GAIN=curated_amp_gains_2020-09-16.json         # get GAIN from this file
I think you can just delete the `[ANALYZE]` and `[ANALYSIS_RUNS]` sections.

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_large.cfg
> +FILTERCONFIG = /gpfs/slac/lsst/fs2/u1/devel/ccs/bot-eotest-configs/Run6/calib.cfg
Please update this path to 
```
FILTERCONFIG = /home/ccs/bot-eotest-configs/Run7/calib.cfg
```

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_large.cfg
> +FLAT=15     90000,  # number of electrons/pixel, ND filter
This comment, `# number of electrons/pixel, ND filter`, looks wrong.

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_large.cfg
> +     15     200000,
Can you add a final `\n` (newline) to this file?

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_medium.cfg
> +FILTERCONFIG = /gpfs/slac/lsst/fs2/u1/devel/ccs/bot-eotest-configs/Run6/calib.cfg
This needs to be updated.

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_short.cfg
> +FILTERCONFIG = /gpfs/slac/lsst/fs2/u1/devel/ccs/bot-eotest-configs/Run6/calib.cfg
Please update.

2024-08-27 22:18 UTC, jchiang87 commented on Run7/step05/Persistence_short.cfg
> +      red  120000    1,    # wavelength filter, signal(e-), count
Please add a newline.

2024-08-27 22:43 UTC, jbanovetz commented
Thank you for looking at it, I will make those changes.

> I'm curious why a `flat` acquisition is used for `Persistence_large.cfg`, but `sflat` for the other two.

For this one, I wanted two flats taken at the same flux level so that I could average them to beat down any read or shot noise. I could change it to sflats and just copy every flux level X number of times (maybe 3) if that would help with processing.

2024-08-27 23:48 UTC, jchiang87 approved these changes
lgtm.

2024-08-28 13:34 UTC, jbanovetz commented
Looking at the output of Seth's code I don't think that it is picking up the `DARKINTERRUPT` command as the `Persistence_large.cfg` is only taking ~25 minutes right now and it should have 8, 15 second darks between flat images (rough estimate would be around 205 mintues). I think the configs are good to go but we might want to change that timing script at some point.

2024-08-28 13:44 UTC, jchiang87 commented
sure, I don't think the point was to get the timing results though, but rather to do simple syntax checking of the file.

2024-08-28 15:41 UTC, seanmacb commented
[Reference for changes](https://rubinobs.atlassian.net/wiki/spaces/CAM/pages/60358677)

2024-08-28 16:39 UTC, jbanovetz commented
After some discussion in Aaron's weekly meeting, I changed the Large and Short configs to match what he was thinking.

2024-08-28 20:20 UTC, sethdigel commented
I'd recommend removing the comma at the end of the last line of lists of flats/sflats.  I recall that fp_srcipts does not like it.

2024-08-28 23:02 UTC, jbanovetz commented
Removed the commas and will now merge

2024-08-28 23:03 UTC, merged